{% if workers.count() > 0 %}
    <h3 class='p-4'>Choose worker to unassign/remove</h3>

    <div class="container">

        <div class="row font-weight-bold bg-light border p-2">
            <div class="col">
                First Name
            </div>
            <div class="col">
                Last Name
            </div>
            <div class="col">
                Email
            </div>
        </div>

        {% for worker in workers %}

            <div class="row border border-top-0 p-1">
                <div class="col">
                    {{ link_to(['for': 'unAssignWorker', 'id': worker.id], worker.firstName, 'class': 'text-dark') }}
                </div>
                <div class="col">
                    {{ link_to(['for': 'unAssignWorker', 'id': worker.id], worker.lastName, 'class': 'text-dark') }}
                </div>
                <div class="col">
                    {{ link_to(['for': 'unAssignWorker', 'id': worker.id], worker.email, 'class': 'text-dark') }}
                </div>
            </div>

        {% endfor %}

    </div>
{% else %}
    <h3 class='p-4'>None of the registered workers are assigned</h3>
{% endif %}
