<h3>Choose worker to edit</h3>

<div class="container">

    <div class="row font-weight-bold bg-light border p-2">
        <div class="col">
            First Name
        </div>
        <div class="col">
            Last Name
        </div>
        <div class="col">
            Email
        </div>
    </div>

{% for worker in workers%}
        <div class="row border border-top-0 p-1">
            <div class="col">
                {{ link_to(['for': 'editWorker', 'id': worker.id], worker.firstName, 'class': 'text-dark') }}
            </div>
            <div class="col">
                {{ link_to(['for': 'editWorker', 'id': worker.id], worker.lastName, 'class': 'text-dark') }}
            </div>
            <div class="col">
                {{ link_to(['for': 'editWorker', 'id': worker.id], worker.email, 'class': 'text-dark') }}
            </div>
        </div>
{% endfor %}

</div>
