<h3>Edit worker</h3>

{{ form('worker/edit', 'method': 'post') }}
<fieldset>

    <div class='form-group'>
        <label for='id'>Select worker</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                <div class='controls'>
                    {{ select(
                    'id',
                    workers,
                    'using': ['id', 'fullName'],
                    'required': 'true',
                    'class': 'form-control',
                    'useEmpty': 'true',
                    'emptyText' : 'No worker is selected',
                    'emptyValue' : ''
                    )}}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='lastName'>Last name</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and errors.filter('lastName')|length > 0 %}
                <div class='text-danger'>
                    {{ errors.filter('lastName')[0].getMessage() }}
                </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('lastName', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='firstName'>First name</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and  errors.filter('firstName')|length > 0 %}
                <div class='text-danger'>
                    {{ errors.filter('firstName')[0].getMessage() }}
                </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('firstName', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='email'>Email</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and  errors.filter('email')|length > 0 %}
                <div class='text-danger'>
                    {{ errors.filter('email')[0].getMessage() }}
                </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('email', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        {{ submit_button('Edit worker', 'class': 'btn btn-primary btn-large', 'name': 'submit') }}
    </div>
</fieldset>
{{  endform() }}
