<h3>Register worker</h3>

{{ form('worker/register', 'method': 'post') }}
<fieldset>
    <div class='form-group'>
        <label for='lastName'>Last name</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and errors.filter('lastName')|length > 0 %}
                    <div class='text-danger'>
                        {{ errors.filter('lastName')[0].getMessage() }}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('lastName', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='firstName'>First name</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and  errors.filter('firstName')|length > 0 %}
                    <div class='text-danger'>
                        {{ errors.filter('firstName')[0].getMessage() }}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('firstName', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='email'>Email</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and  errors.filter('email')|length > 0 %}
                    <div class='text-danger'>
                        {{ errors.filter('email')[0].getMessage() }}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('email', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='admin'>Type</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                <div class='controls'>
                {{ select(
                    'admin',
                    ['1': 'Admin'],
                    'onchange': 'togglePasswordDisplay(this.value)',
                    'class': 'form-control',
                    'useEmpty': 'true',
                    'emptyText' : 'Worker',
                    'emptyValue' : '0'
                )}}
            </div>
            </div>
        </div>
    </div>

    <div class='form-group' id='pass'>
        <label for='password'>Password</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if errors is defined and  errors.filter('password')|length > 0 %}
                    <div class='text-danger'>
                        {{ errors.filter('password')[0].getMessage() }}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ password_field('password', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>
    <div class='form-group'>
        {{ submit_button('Register worker', 'class': 'btn btn-primary btn-large', 'name': 'submit') }}
    </div>
</fieldset>
{{  endform() }}

<!--Include main js file-->
{{ javascript_include('js/register_worker.js') }}
