<h3>Register worker</h3>

{{ form('worker/register', 'method': 'post') }}
<fieldset>
    <div class='form-group'>
        <label for='lastName'>Last name</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if hasErrors and errors.filter('lastName')|length > 0 %}
                    <div class='text-danger'>
                        {% for index, error in errors.filter('lastName') %}
                            {{ error.getMessage() }}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('lastName', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='firstName'>First name</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if hasErrors == 1 and  errors.filter('firstName')|length > 0 %}
                    <div class='text-danger'>
                        {% for index, error in errors.filter('firstName') %}
                            {{ error.getMessage() }}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('firstName', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        <label for='email'>Email</label>
        <div class='row justify-content-center'>
            <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                {% if hasErrors and  errors.filter('email')|length > 0 %}
                    <div class='text-danger'>
                        {% for index, error in errors.filter('email') %}
                            {{ error.getMessage() }}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class='controls'>
                    {{ text_field('email', 'class': 'form-control') }}
                </div>
            </div>
        </div>
    </div>

    <div class='form-group'>
        {{ submit_button('Register worker', 'class': 'btn btn-primary btn-large', 'name': 'submit') }}
    </div>
</fieldset>
{{  endform() }}
