<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <span class="navbar-brand mb-0 h1 font-weight-bold">Assignments:</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav nav-fill w-100 mr-auto">
            <li class="nav-item">
                {{ link_to('', 'Actual', 'class': 'nav-link font-weight-bold') }}</li>
            </li>
            <li class="nav-item">
                {{ link_to('history', 'History', 'class': 'nav-link font-weight-bold') }}</li>
            </li>
            <li class="nav-item">
                {{ link_to('worker/history', 'Worker', 'class': 'nav-link font-weight-bold') }}</li>
            </li>
            <li class="nav-item">
                {{ link_to('project/history', 'Project', 'class': 'nav-link font-weight-bold') }}</li>
            </li>

        </ul>
    </div>
</nav>