<h3 class='p-4'>Edit project</h3>

{{ form(['for': 'editProject', 'id': project.id], 'method': 'post', 'id': 'project_edit_form') }}

    <fieldset>
            <div class='form-group'>
            <label for='name'>Name</label>
            <div class='row justify-content-center'>
                <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                    {% if hasErrors and errors.filter('name')|length > 0 %}
                    <div class='text-danger'>
                        {% for index, error in errors.filter('name') %}
                            {{ error.getMessage() }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class='controls'>
                        {{ text_field('id', 'class': 'form-control', 'value': project.id, 'hidden': true) }}
                        {% if hasErrors %}
                            {{ text_field('name', 'class': 'form-control', 'value': request.getPost('name')) }}
                        {% else %}
                            {{ text_field('name', 'class': 'form-control', 'value': project.name) }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class='form-group'>
            <label for='description'>Description</label>
            <div class='row justify-content-center'>
                <div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>
                    {% if hasErrors == 1 and  errors.filter('description')|length > 0 %}
                    <div class='text-danger'>
                        {% for index, error in errors.filter('description') %}
                            {{ error.getMessage() }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class='controls'>
                        {% if hasErrors %}
                            {{ text_field('description', 'class': 'form-control', 'value': request.getPost('description')) }}
                        {% else %}
                            {{ text_field('description', 'class': 'form-control', 'value': project.description) }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class='form-group'>
            {{ submit_button('Update project', 'class': 'btn btn-primary btn-large', 'name': 'submit') }}
        </div>
    </fieldset>

{{  endform() }}
