<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Gantt Dashboard</title>
    {{ stylesheet_link('https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css') }}
</head>
<body>
    <div class="container-fluid">
        {{ partial('partials/menu') }}

        {%if true === session.has('admin') %}
            {{ partial('partials/adminmenu') }}
        {% endif %}
        <hr />
    </div>

    <div class="container-fluid text-center">
        {{ flashSession.output() }}
        {{ content() }}
    </div>

    <div class="container-fluid text-center">
        <hr />
        <p>Gantt Dashboard &copy; p4b.ro</p>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    {{ javascript_include('https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js') }}
    <!-- Latest compiled and minified Popper -->
    {{ javascript_include('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js') }}
    <!-- Latest compiled and minified JavaScript -->
    {{ javascript_include('https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js') }}

</body>
</html>
