<!DOCTYPE html>
<html>
    <head>
        <title>Gantt chart dashboard</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <div class="container">
            <div class="admin_menu">
                <?php
                echo $this->tag->linkTo(['registerworker', 'Register Worker', 'class' => 'button a_menu adm']), ' ';
                echo $this->tag->linkTo(['registerproject', 'Register Project', 'class' => 'button a_menu adm']), ' ';

                echo $this->tag->linkTo(['editworker', 'Edit Worker', 'class' => 'button a_menu adm']), ' ';
                echo $this->tag->linkTo(['editproject', 'Edit Project', 'class' => 'button a_menu adm']), ' ';

                echo $this->tag->linkTo(['assignworker', 'Assign Worker to Project', 'class' => 'button a_menu adm']), ' ';

                echo $this->tag->linkTo(['unassignworker', 'Remove Worker from Project', 'class' => 'button a_menu adm']), ' ';

                echo $this->tag->linkTo(['logout', 'Logout', 'class' => 'button a_menu adm']), ' ';?>
            </div>
            <br />
            <?php
                echo $this->tag->linkTo(['', 'Actual Assignments', 'class' => 'button a_menu']), ' ';
                echo $this->tag->linkTo(['history', 'History Assignments', 'class' => 'button a_menu']), ' ';
                echo $this->tag->linkTo(['workerhistory', 'Worker Assignments', 'class' => 'button a_menu']), ' ';
                echo $this->tag->linkTo(['projecthistory', 'Project Assignments', 'class' => 'button a_menu']), ' ';

                echo $this->getContent(); ?>
        </div>
    </body>
</html>
