<div class="page-header text-center">
    <?php
    if (true === isset($_SESSION['worker_session'])) {
        echo Phalcon\Tag::linkTo(['worker/register', 'Register Worker', 'class' => 'button a_menu adm', "local" => false]), ' ';
        echo Phalcon\Tag::linkTo(['project/register', 'Register Project', 'class' => 'button a_menu adm', "local" => false]), ' ';

        echo Phalcon\Tag::linkTo(['worker/edit', 'Edit Worker', 'class' => 'button a_menu adm', "local" => false]), ' ';
        echo Phalcon\Tag::linkTo(['project/edit', 'Edit Project', 'class' => 'button a_menu adm', "local" => false]), ' ';

        echo Phalcon\Tag::linkTo(['worker/assign', 'Assign Worker to Project', 'class' => 'button a_menu adm', "local" => false]), ' ';

        echo Phalcon\Tag::linkTo(['worker/unassign', 'Remove Worker from Project', 'class' => 'button a_menu adm', "local" => false]), ' ';

        echo Phalcon\Tag::linkTo(['worker/logout', 'Logout', 'class' => 'button a_menu adm', "local" => false]), ' ';
    }
    echo '<br />';

    echo Phalcon\Tag::linkTo(['/', 'Actual Assignments', 'class' => 'button a_menu', "local" => false]), ' ';
    echo Phalcon\Tag::linkTo(['history', 'History Assignments', 'class' => 'button a_menu', "local" => false]), ' ';
    echo Phalcon\Tag::linkTo(['worker/history', 'Worker Assignments', 'class' => 'button a_menu', "local" => false]), ' ';
    echo Phalcon\Tag::linkTo(['project/history', 'Project Assignments', 'class' => 'button a_menu', "local" => false]), ' ';
    ?>
</div>

<div class="container">
    <?php echo $this->getContent(); ?>
</div>

<div class="footer-copyrigh">
    <hr>
    <p class="text-center"> Gantt Dashboard &#9400; p4b.ro</p>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

